on: [push, pull_request]

name: macOS Build

jobs:
  build:
    name: Build
    runs-on: macos-latest
    strategy:
      matrix:
        python-version: [2.7, 3.5, 3.6, 3.7, 3.8]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/checkout@v2
        with:
          repository: facebookresearch/fastText
          ref: v0.9.2
          path: fastText
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"
      - name: Build macOS wheels
        run: |
            sed -i '' "s/name='fasttext',/name='fasttext-wheel',/" fastText/setup.py
            pip install wheel delocate
            cd fastText
            python setup.py bdist_wheel
            delocate-wheel -w ../dist -v dist/fasttext*.whl
            cd ..
            ls -lrth dist/
      - name: Publish macOS package
        if: github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags')
        run: |
            pip install twine
            TWINE_USERNAME=__token__ TWINE_PASSWORD=${{ secrets.pypi_password }} twine upload --skip-existing dist/*
