on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

name: Windows Build

jobs:
  build:
    name: Build
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.7, 3.8, 3.9, '3.10', '3.11', '3.12']
        arch: [x64, x86]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/checkout@v4
        with:
          repository: messense/fastText
          ref: main
          path: fastText
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          architecture: ${{ matrix.arch }}
          python-version: ${{ matrix.python-version }}
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"
      - name: Install visualcpp-build-tools
        run: choco install -y visualcpp-build-tools
      - name: Build Windows wheels
        run: |
            sed -i "s/name='fasttext',/name='fasttext-wheel',/" fastText/setup.py
            pip install build
            cd fastText
            python -m build --wheel -o ../dist
            cd ..
            ls -lrth dist/
        shell: bash
      - name: Upload wheels
        uses: actions/upload-artifact@v3
        with:
          name: windows-wheels
          path: dist/fasttext_wheel-*.whl
      - name: Publish Windows package
        if: github.event_name == 'workflow_dispatch' || startsWith(github.event.ref, 'refs/tags')
        run: |
            pip install twine
            TWINE_USERNAME=__token__ TWINE_PASSWORD=${{ secrets.pypi_password }} twine upload --skip-existing dist/*
        shell: bash
